node nightmare lists/BlackIronHack-Phase1.json
node nightmare lists/BlackIronHack-Phase2.json
node nightmare lists/BlackIronHack-Phase3.json
node nightmare lists/BlackIronHack-Phase4.json
node nightmare lists/GoldIronHack-Phase1.json
node nightmare lists/GoldIronHack-Phase2.json
node nightmare lists/GoldIronHack-Phase3.json
node nightmare lists/GoldIronHack-Phase4.json
node nightmare lists/GreenIronHack-Phase1.json
node nightmare lists/GreenIronHack-Phase2.json
node nightmare lists/GreenIronHack-Phase3.json
node nightmare lists/GreenIronHack-Phase4.json
